<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php $this->vw('name'); ?></title>
    <?php $this->extend('head_vendors'); ?>
</head>
<body class="container-fluid d-flex flex-column">


    <?php $this->extend('header'); ?>
    
    <div class="row flex-grow-1 justify-content-around">


        
    </div>

    <?php $this->vendor('js', 'jquery.min'); ?>
    <?php $this->vendor('js', 'popper.min'); ?>
    <?php $this->vendor('js', 'bootstrap/js/bootstrap.min'); ?>

</body>
</html>